import { useState } from "react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import useInfiniteScroll from "react-infinite-scroll-hook";

import client from "@d20/react-query/client";
import {
  GetPostsDocument,
  GetPostsQuery,
  PostConnection,
  useGetPostsQuery,
} from "@d20/generated/graphql";
import {
  QueryClient,
  dehydrate,
  useQuery,
  useQueryClient,
} from "@tanstack/react-query";

// import { newPostIncoming } from "@d20/reactivities/posts";

import Feed from "@d20/components/Feed";
import { PostLoader } from "@d20/components/Loaders";
import Postbox from "@d20/components/Postbox";

type Props = {
  posts: PostConnection;
};

const Home: NextPage<Props> = () => {
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const queryClient = useQueryClient();

  const { data } = useQuery<GetPostsQuery | undefined>(
    useGetPostsQuery.getKey(),
    useGetPostsQuery.fetcher(client, { first: 4 })
  );

  const posts = data?.posts;
  const hasNextPage: boolean = posts?.pageInfo?.hasNextPage!;

  const loadItems = async () => {
    const data = await client.request<GetPostsQuery | undefined>(
      GetPostsDocument,
      {
        first: 4,
        after: posts?.pageInfo?.endCursor,
      }
    );

    queryClient.setQueryData<GetPostsQuery | undefined>(
      useGetPostsQuery.getKey(),
      {
        posts: {
          edges: [...posts?.edges!, ...data?.posts?.edges!],
          pageInfo: {
            ...posts?.pageInfo,
            ...data?.posts?.pageInfo!,
          },
        },
      }
    );

    setIsLoading(false);
  };

  const handleLoadMore = async () => {
    hasNextPage && loadItems();
  };

  const [sentryRef] = useInfiniteScroll({
    hasNextPage,
    loading: isLoading,
    onLoadMore: handleLoadMore,
  });

  return (
    <div className="mx-auto my-7 max-w-5xl">
      <Head>
        <title>Reddit 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Postbox />
      {/* 
      {newPostIncoming() && <PostLoader length={1} />}
      */}

      <Feed
        posts={posts?.edges}
        loading={isLoading || (hasNextPage as boolean)}
        loadingRef={sentryRef}
      />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery<GetPostsQuery | undefined>(
    useGetPostsQuery.getKey(),
    useGetPostsQuery.fetcher(client, { first: 4 })
  );

  return {
    props: {
      dehydratedState: JSON.parse(JSON.stringify(dehydrate(queryClient))),
    },
  };
};

export default Home;
