import { use, useCallback } from "react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import client from "@d20/react-query/client";
import useInfiniteScroll from "react-infinite-scroll-hook";

import {
  GetPostsDocument,
  GetPostsQuery,
  useGetPostsQuery,
} from "@d20/generated/graphql";
import {
  QueryClient,
  dehydrate,
  useInfiniteQuery,
} from "@tanstack/react-query";
import Feed from "@d20/components/Feed";
// import { newPostIncoming } from "@d20/reactivities/posts";

// import PostBox from "@d20/Components/Postbox";
// import Feed from "@d20/Components/Feed";
// import { PostLoader } from "@d20/Components/Loaders";

const Home: NextPage = () => {
  const { data, isLoading, fetchNextPage, hasNextPage } = useInfiniteQuery(
    useGetPostsQuery.getKey(),
    ({ pageParam = undefined }) => {
      return client.request<GetPostsQuery>(GetPostsDocument, {
        first: 4,
        after: pageParam,
      });
    },
    {
      getNextPageParam: (lastPage) => {
        if (lastPage?.posts?.pageInfo.hasNextPage) {
          return lastPage?.posts?.pageInfo.endCursor;
        }
        return undefined;
      },
    }
  );

  const posts = data?.pages?.map((page) => page.posts?.edges).flat() ?? [];

  console.log("posts", posts);
  // const hasNextPage: boolean = data?.posts?.pageInfo?.hasNextPage!;

  // console.log("hasNextPage", hasNextPage);
  // console.log("isLoading", isLoading);

  const handleLoadMore = () => {
    hasNextPage && fetchNextPage();
  };

  // const [sentryRef] = useInfiniteScroll({
  //   hasNextPage,
  //   isLoading,
  //   onLoadMore: handleLoadMore,
  // });

  return (
    <div className="mx-auto my-7 max-w-5xl">
      <Head>
        <title>Reddit 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>React Clone: React Query</h1>
      {/* <PostBox />
      {newPostIncoming() && <PostLoader length={1} />}
      */}
      <button onClick={handleLoadMore}>Load More</button>

      <Feed
        posts={posts}
        // loading={loading || hasNextPage}
        // loadingRef={sentryRef}
      />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const queryClient = new QueryClient();

  await queryClient.fetchQuery(
    useGetPostsQuery.getKey(),
    useGetPostsQuery.fetcher(client, { first: 4 })
  );

  return {
    props: {
      dehydratedState: JSON.parse(JSON.stringify(dehydrate(queryClient))),
    },
  };
};

export default Home;
